name: .NET Core Build and Publish

on:
  pull_request:

env:
  NETCORE_VERSION: '7'  
  GIT_REPO_ROOT: src
  MAJOR_MINOR_VERSION: 1.0.
  SOLUTION_FILE: DotnetBuildMetrics.sln
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

jobs: 

  build:
    name: Build Package 
    runs-on: windows-latest # using windows agent for net472 build.

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      working-directory: ${{ env.GIT_REPO_ROOT }}        
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{ env.GIT_REPO_ROOT }}        
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Debug --no-restore
